pipeline: stable_diffusion_xl
base_model_id: stabilityai/stable-diffusion-xl-base-1.0
unet:
  repo_name: ByteDance/SDXL-Lightning
  ckpt_name: sdxl_lightning_8step_unet.safetensors
scheduler: euler_discrete
timesteps: [999., 874., 749., 624., 499., 374., 249., 124.]
saved_steps: [0, 1, 2, 3, 4, 5, 6, 7]
text_embedding_dim: 768
image_shape: [4, 64, 64]